// This file is generated by init-app. Do not modify the interface.
// init-app will overwrite this file with actual dictionary data.

export interface DictItem {
  label: string
  value: string
  color?: string
}

export const dictionaries: Record<string, DictItem[]> = {}
